project_id = "wmclgyqfocssfmdfkzne"

[functions.get-image]
verify_jwt = false

[functions.create-payment-order]
verify_jwt = true

[functions.verify-payment]  
verify_jwt = true

[functions.check-user-credits]
verify_jwt = true