// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmclgyqfocssfmdfkzne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY2xneXFmb2Nzc2ZtZGZrem5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDgzODQsImV4cCI6MjA3MTgyNDM4NH0.3Hh9-in8v3N3vxoO84iruiqBd8DHd9RA3S94drwuqCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});